x-default-isaac-lab-template-environment: &default-isaac-lab-template-environment
  - OMNI_KIT_ALLOW_ROOT=1
  - DISPLAY=${DISPLAY:-:0}
  - XAUTHORITY=${XAUTHORITY:-/root/.Xauthority}
  - QT_X11_NO_MITSHM=1
  - NVIDIA_VISIBLE_DEVICES=all
  - NVIDIA_DRIVER_CAPABILITIES=all
  - ROS_DISTRO=jazzy
  - ROS_SETUP=/opt/ros/jazzy/setup.bash
  - ROS_HOME=/workspace/.ros
  - ROS_LOG_DIR=/workspace/.ros/log

x-default-isaac-lab-template-deploy: &default-isaac-lab-template-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  isaac-lab-template:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACLAB_BASE_IMAGE_ARG=${ISAACLAB_BASE_IMAGE:-isaac-lab-base}
        - DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH_ARG=${DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH:-/workspace/isaaclab_extension_template}
    image: isaac-lab-template
    container_name: isaac-lab-template
    volumes:
      - type: bind
        source: /mnt/data/repos/unitree_rl_lab
        target: ${DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH:-/workspace/isaaclab_extension_template}
      - type: bind
        source: /mnt/data
        target: /workspace/data
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${XAUTHORITY:-/tmp/.docker.xauth}
        target: ${XAUTHORITY:-/root/.Xauthority}
        read_only: true
    network_mode: host
    environment: *default-isaac-lab-template-environment
    deploy: *default-isaac-lab-template-deploy
    restart: unless-stopped
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
