"""Run a trained G1 velocity policy in Isaac Lab using UDP command I/O.

This avoids importing ROS 2 Python packages inside Isaac's Python runtime.
Use ``scripts/_internal/bridge/ros2_g1_udp_bridge.py`` in a separate system-Python process to
translate ROS 2 ``/cmd_vel`` <-> UDP.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import pathlib
import socket
import sys
import time
from dataclasses import dataclass
from importlib.metadata import version

from isaaclab.app import AppLauncher

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "rsl_rl"))
import cli_args  # isort: skip
sys.path.pop(0)

parser = argparse.ArgumentParser(description="Play a G1 velocity policy with UDP cmd_vel input.")
parser.add_argument("--task", type=str, default="Unitree-G1-29dof-Velocity")
parser.add_argument("--num_envs", type=int, default=1)
parser.add_argument("--disable_fabric", action="store_true", default=False)
parser.add_argument("--real-time", action="store_true", default=True)
parser.add_argument("--cmd_udp_port", type=int, default=15000)
parser.add_argument("--odom_udp_host", type=str, default="127.0.0.1")
parser.add_argument("--odom_udp_port", type=int, default=15001)
parser.add_argument("--manip_udp_port", type=int, default=15002)
parser.add_argument("--disable_manipulation_udp", action="store_true", default=False)
parser.add_argument("--arm_udp_port", type=int, default=15003)
parser.add_argument("--disable_arm_udp", action="store_true", default=False)
parser.add_argument("--arm_action_scale", type=float, default=0.25)
parser.add_argument(
    "--arm_max_delta_per_step",
    type=float,
    default=0.0015,
    help=(
        "Maximum per-simulation-step change, in radians, applied to each arm "
        "joint override. This keeps MoveIt Servo arm targets from kicking the "
        "locomotion policy and destabilizing the base during button pressing."
    ),
)
parser.add_argument("--command_timeout", type=float, default=2.0)
parser.add_argument("--disable_command_timeout", action="store_true", default=False)
parser.add_argument(
    "--episode_length_s",
    type=float,
    default=3600.0,
    help="Runtime episode length for continuous navigation demos. Prevents play-time timeout resets.",
)
parser.add_argument("--min_vx", type=float, default=-0.2)
parser.add_argument("--max_vx", type=float, default=0.5)
parser.add_argument("--max_abs_vy", type=float, default=0.10)
parser.add_argument("--max_abs_wz", type=float, default=0.15)
parser.add_argument("--command_print_interval", type=int, default=100)
parser.add_argument("--hand_debug_interval", type=int, default=50)
parser.add_argument("--no_auto_camera", action="store_true", default=False)
parser.add_argument(
    "--scene_json",
    type=str,
    default="",
    help="Optional obstacle scene JSON generated by create_substation_nav2_map.py.",
)
cli_args.add_rsl_rl_args(parser)
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import gymnasium as gym
import torch
from rsl_rl.runners import OnPolicyRunner

import isaaclab_tasks  # noqa: F401
import unitree_rl_lab.tasks  # noqa: F401
from isaaclab.envs import DirectMARLEnv, multi_agent_to_single_agent
from isaaclab.utils.assets import retrieve_file_path
from isaaclab_rl.rsl_rl import RslRlOnPolicyRunnerCfg, RslRlVecEnvWrapper
from isaaclab_tasks.utils import get_checkpoint_path

from unitree_rl_lab.utils.parser_cfg import parse_env_cfg
from unitree_rl_lab.utils.rsl_rl_stability import load_runner_checkpoint_compat

try:
    from isaacsim.core.utils.viewports import set_camera_view
except ModuleNotFoundError:
    set_camera_view = None


def get_obs(vec_env):
    obs = vec_env.get_observations()
    if version("rsl-rl-lib").startswith("2.3."):
        obs, _ = obs
    return obs


def resolve_checkpoint(agent_cfg: RslRlOnPolicyRunnerCfg) -> str:
    log_root_path = os.path.abspath(os.path.join("logs", "rsl_rl", agent_cfg.experiment_name))
    if args_cli.checkpoint:
        return retrieve_file_path(args_cli.checkpoint)
    return get_checkpoint_path(log_root_path, agent_cfg.load_run, agent_cfg.load_checkpoint)


def clamp_to_policy_range(command: torch.Tensor, env_cfg) -> torch.Tensor:
    ranges = env_cfg.commands.base_velocity.limit_ranges
    command[:, 0] = command[:, 0].clamp(ranges.lin_vel_x[0], ranges.lin_vel_x[1])
    command[:, 1] = command[:, 1].clamp(ranges.lin_vel_y[0], ranges.lin_vel_y[1])
    command[:, 2] = command[:, 2].clamp(ranges.ang_vel_z[0], ranges.ang_vel_z[1])
    return command


def enforce_command(vec_env, command: torch.Tensor) -> torch.Tensor:
    term = vec_env.unwrapped.command_manager.get_term("base_velocity")
    term.vel_command_b[:] = command
    if hasattr(term, "is_standing_env"):
        term.is_standing_env[:] = torch.all(torch.isclose(command, torch.zeros_like(command)), dim=1)
    if hasattr(term, "is_heading_env"):
        term.is_heading_env[:] = False
    if hasattr(term, "heading_target"):
        term.heading_target[:] = 0.0
    if hasattr(term, "time_left"):
        term.time_left[:] = 1.0e9
    return vec_env.unwrapped.command_manager.get_command("base_velocity").clone()


def set_camera_to_robot(vec_env) -> None:
    if args_cli.headless or args_cli.no_auto_camera or set_camera_view is None:
        return
    robot = vec_env.unwrapped.scene["robot"]
    root_pos = robot.data.root_pos_w[0].detach().cpu()
    target = [float(root_pos[0]), float(root_pos[1]), float(root_pos[2] + 0.7)]
    eye = [target[0] + 3.0, target[1] - 3.0, target[2] + 1.8]
    set_camera_view(eye, target)
    print(f"[udp-policy] camera eye={eye} target={target}")


def yaw_from_quat_wxyz(quat_wxyz) -> float:
    w, x, y, z = [float(value) for value in quat_wxyz]
    siny_cosp = 2.0 * (w * z + x * y)
    cosy_cosp = 1.0 - 2.0 * (y * y + z * z)
    return math.atan2(siny_cosp, cosy_cosp)


def odom_xy_to_world(x: float, y: float, origin_x: float, origin_y: float, origin_yaw: float) -> tuple[float, float]:
    cos_yaw = math.cos(origin_yaw)
    sin_yaw = math.sin(origin_yaw)
    return (
        origin_x + cos_yaw * x - sin_yaw * y,
        origin_y + sin_yaw * x + cos_yaw * y,
    )


def odom_point_to_world(point: list[float], origin_x: float, origin_y: float, origin_yaw: float) -> list[float]:
    world_x, world_y = odom_xy_to_world(float(point[0]), float(point[1]), origin_x, origin_y, origin_yaw)
    return [world_x, world_y, float(point[2])]


def safe_prim_name(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)


@dataclass
class SceneRuntime:
    stage: object
    origin_x: float
    origin_y: float
    origin_yaw: float
    prim_paths_by_name: dict[str, str]
    centers_by_name: dict[str, list[float]]
    manipulation: dict


def spawn_static_box(
    stage,
    prim_path: str,
    center: list[float],
    size: list[float],
    yaw: float,
    color: tuple[float, float, float],
) -> None:
    from pxr import Gf, UsdGeom, UsdPhysics

    cube = UsdGeom.Cube.Define(stage, prim_path)
    cube.CreateSizeAttr(1.0)
    xform = UsdGeom.Xformable(cube.GetPrim())
    xform.AddTranslateOp().Set(Gf.Vec3d(float(center[0]), float(center[1]), float(center[2])))
    xform.AddRotateZOp().Set(math.degrees(float(yaw)))
    xform.AddScaleOp().Set(Gf.Vec3f(float(size[0]), float(size[1]), float(size[2])))
    cube.CreateDisplayColorAttr([Gf.Vec3f(*color)])
    UsdPhysics.CollisionAPI.Apply(cube.GetPrim())


def set_box_center(stage, prim_path: str, center: list[float]) -> bool:
    from pxr import Gf, UsdGeom

    prim = stage.GetPrimAtPath(prim_path)
    if not prim.IsValid():
        return False
    xform = UsdGeom.Xformable(prim)
    for op in xform.GetOrderedXformOps():
        if op.GetOpType() == UsdGeom.XformOp.TypeTranslate:
            op.Set(Gf.Vec3d(float(center[0]), float(center[1]), float(center[2])))
            return True
    xform.AddTranslateOp().Set(Gf.Vec3d(float(center[0]), float(center[1]), float(center[2])))
    return True


def set_box_color(stage, prim_path: str, color: tuple[float, float, float]) -> bool:
    from pxr import Gf, UsdGeom

    prim = stage.GetPrimAtPath(prim_path)
    if not prim.IsValid():
        return False
    cube = UsdGeom.Cube(prim)
    cube.CreateDisplayColorAttr([Gf.Vec3f(*color)])
    return True


def transform_manipulation_metadata(manipulation: dict, origin_x: float, origin_y: float, origin_yaw: float) -> dict:
    result = json.loads(json.dumps(manipulation))
    for section in ("table", "pick_object", "place_target"):
        if section not in result:
            continue
        for key, value in list(result[section].items()):
            if key.endswith("_pose") or key.endswith("_goal") or key == "center":
                if isinstance(value, list) and len(value) >= 3:
                    world_xy = odom_xy_to_world(float(value[0]), float(value[1]), origin_x, origin_y, origin_yaw)
                    if key.endswith("_goal"):
                        result[section][key] = [world_xy[0], world_xy[1], float(value[2]) + origin_yaw]
                    else:
                        result[section][key] = [world_xy[0], world_xy[1], float(value[2])]
    return result


def spawn_obstacle_scene(vec_env, scene_json: str) -> SceneRuntime | None:
    if not scene_json:
        return None
    scene_path = pathlib.Path(scene_json)
    if not scene_path.is_file():
        raise FileNotFoundError(f"scene_json not found: {scene_json}")

    import omni.usd

    stage = omni.usd.get_context().get_stage()
    robot = vec_env.unwrapped.scene["robot"]
    root_pos = robot.data.root_pos_w[0].detach().cpu().tolist()
    root_quat = robot.data.root_quat_w[0].detach().cpu().tolist()
    origin_x = float(root_pos[0])
    origin_y = float(root_pos[1])
    origin_yaw = yaw_from_quat_wxyz(root_quat)

    scene = json.loads(scene_path.read_text(encoding="utf-8"))
    root_prim = "/World/SubstationStatic"
    colors = {
        "wall": (0.30, 0.32, 0.34),
        "cabinet": (0.12, 0.22, 0.30),
        "table": (0.45, 0.30, 0.18),
        "pick_cube": (0.90, 0.18, 0.12),
        "place_block": (0.15, 0.42, 0.78),
        "button": (1.0, 0.02, 0.02),
    }
    prim_paths_by_name: dict[str, str] = {}
    centers_by_name: dict[str, list[float]] = {}
    for index, obstacle in enumerate(scene.get("obstacles", []), start=1):
        center = obstacle["center"]
        size = obstacle["size"]
        world_center = odom_point_to_world(center, origin_x, origin_y, origin_yaw)
        world_yaw = origin_yaw + float(obstacle.get("yaw", 0.0))
        kind = obstacle.get("kind", "cabinet")
        name = obstacle.get("name", f"box_{index}")
        safe_name = safe_prim_name(name)
        prim_path = f"{root_prim}/{safe_name}"
        spawn_static_box(
            stage,
            prim_path,
            world_center,
            size,
            world_yaw,
            colors.get(kind, (0.2, 0.2, 0.2)),
        )
        prim_paths_by_name[name] = prim_path
        centers_by_name[name] = world_center

    for button in scene.get("button_demo", {}).get("buttons", []):
        name = str(button.get("name", "button"))
        normal = [float(v) for v in button.get("normal", [0.0, -1.0, 0.0])]
        press_pose = [float(v) for v in button.get("press_pose", button.get("center", [0.0, 0.0, 0.0]))]
        marker_specs = [
            (f"{name}_ik_button_center", press_pose, (1.0, 0.0, 0.0)),
            (
                f"{name}_ik_pre_target",
                [
                    press_pose[0] + normal[0] * 0.16,
                    press_pose[1] + normal[1] * 0.16,
                    press_pose[2],
                ],
                (1.0, 0.85, 0.0),
            ),
            (
                f"{name}_ik_contact_target",
                [
                    press_pose[0] - normal[0] * 0.04,
                    press_pose[1] - normal[1] * 0.04,
                    press_pose[2],
                ],
                (0.0, 0.9, 0.15),
            ),
        ]
        for marker_name, marker_odom, color in marker_specs:
            marker_world = odom_point_to_world(marker_odom, origin_x, origin_y, origin_yaw)
            prim_path = f"{root_prim}/{safe_prim_name(marker_name)}"
            spawn_static_box(stage, prim_path, marker_world, [0.06, 0.06, 0.06], origin_yaw, color)
            prim_paths_by_name[marker_name] = prim_path
            centers_by_name[marker_name] = marker_world

    print(
        f"[udp-policy] spawned static obstacle scene from {scene_path} "
        f"with {len(scene.get('obstacles', []))} boxes"
    )
    return SceneRuntime(
        stage=stage,
        origin_x=origin_x,
        origin_y=origin_y,
        origin_yaw=origin_yaw,
        prim_paths_by_name=prim_paths_by_name,
        centers_by_name=centers_by_name,
        manipulation=transform_manipulation_metadata(
            scene.get("manipulation", {}), origin_x, origin_y, origin_yaw
        ),
    )


class UdpPolicyIO:
    def __init__(self):
        self.cmd_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.cmd_socket.bind(("0.0.0.0", args_cli.cmd_udp_port))
        self.cmd_socket.setblocking(False)
        self.odom_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.odom_target = (args_cli.odom_udp_host, args_cli.odom_udp_port)
        self.latest_cmd = torch.zeros(3, dtype=torch.float32)
        self.last_cmd_wall_time = float("-inf")
        self.received_cmd_count = 0
        self.last_packet_meta = {}

    def poll_command(self, device: torch.device, env_cfg) -> torch.Tensor:
        self._drain_cmd_socket()
        age = self.command_age()
        timed_out = (
            not args_cli.disable_command_timeout
            and (self.received_cmd_count == 0 or age > args_cli.command_timeout)
        )
        cmd = torch.zeros(3, dtype=torch.float32) if timed_out else self.latest_cmd.clone()
        cmd[0] = torch.clamp(cmd[0], args_cli.min_vx, args_cli.max_vx)
        cmd[1] = torch.clamp(cmd[1], -args_cli.max_abs_vy, args_cli.max_abs_vy)
        cmd[2] = torch.clamp(cmd[2], -args_cli.max_abs_wz, args_cli.max_abs_wz)
        cmd = cmd.to(device=device).unsqueeze(0)
        return clamp_to_policy_range(cmd, env_cfg)

    def command_age(self) -> float:
        if self.received_cmd_count == 0:
            return float("inf")
        return time.monotonic() - self.last_cmd_wall_time

    def is_timed_out(self) -> bool:
        age = self.command_age()
        return (
            not args_cli.disable_command_timeout
            and (self.received_cmd_count == 0 or age > args_cli.command_timeout)
        )

    def publish_odom(self, vec_env, sim_time: float) -> None:
        robot = vec_env.unwrapped.scene["robot"]
        payload = {
            "sim_time": sim_time,
            "pos": robot.data.root_pos_w[0].detach().cpu().tolist(),
            "quat_wxyz": robot.data.root_quat_w[0].detach().cpu().tolist(),
            "lin_vel_b": robot.data.root_lin_vel_b[0].detach().cpu().tolist(),
            "ang_vel_b": robot.data.root_ang_vel_b[0].detach().cpu().tolist(),
        }
        if hasattr(robot.data, "joint_names"):
            payload["joint_names"] = list(robot.data.joint_names)
            payload["joint_pos"] = robot.data.joint_pos[0].detach().cpu().tolist()
            payload["joint_vel"] = robot.data.joint_vel[0].detach().cpu().tolist()
        self.odom_socket.sendto(json.dumps(payload).encode("utf-8"), self.odom_target)

    def _drain_cmd_socket(self) -> None:
        while True:
            try:
                data, _ = self.cmd_socket.recvfrom(65535)
            except BlockingIOError:
                return
            try:
                payload = json.loads(data.decode("utf-8"))
            except json.JSONDecodeError as exc:
                print(f"[udp-policy][WARN] bad cmd UDP JSON: {exc}")
                continue
            cmd = payload.get("cmd", [0.0, 0.0, 0.0])
            self.latest_cmd = torch.tensor(cmd[:3], dtype=torch.float32)
            self.last_cmd_wall_time = time.monotonic()
            self.received_cmd_count += 1
            self.last_packet_meta = payload


class ArmOverrideUdpIO:
    RIGHT_ARM_JOINTS = [
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ]

    def __init__(self):
        self.enabled = not args_cli.disable_arm_udp
        self.socket: socket.socket | None = None
        self.latest_positions: dict[str, float] = {}
        self.applied_positions: dict[str, float] = {}
        self.last_update_time = float("-inf")
        self.hold_timeout = 0.35
        self.received_count = 0
        self.joint_indices: dict[str, int] | None = None
        if self.enabled:
            self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.socket.bind(("0.0.0.0", args_cli.arm_udp_port))
            self.socket.setblocking(False)

    def poll(self) -> None:
        if not self.enabled or self.socket is None:
            return
        while True:
            try:
                data, _ = self.socket.recvfrom(65535)
            except BlockingIOError:
                return
            try:
                payload = json.loads(data.decode("utf-8"))
            except json.JSONDecodeError as exc:
                print(f"[udp-policy][WARN] bad arm UDP JSON: {exc}")
                continue
            positions = payload.get("arm_joint_positions", {})
            if not isinstance(positions, dict):
                continue
            filtered = {
                name: float(value)
                for name, value in positions.items()
                if name in self.RIGHT_ARM_JOINTS
            }
            if not filtered:
                continue
            self.latest_positions.update(filtered)
            self.hold_timeout = float(payload.get("hold_timeout", self.hold_timeout))
            self.last_update_time = time.monotonic()
            self.received_count += 1
            if self.received_count <= 5 or self.received_count % 100 == 0:
                print(f"[udp-policy] received arm override count={self.received_count} joints={list(filtered)}")

    def active(self) -> bool:
        if not self.latest_positions:
            return False
        is_active = (time.monotonic() - self.last_update_time) <= self.hold_timeout
        if not is_active:
            self.applied_positions.clear()
        return is_active

    def apply(self, vec_env, actions: torch.Tensor) -> torch.Tensor:
        if not self.enabled or not self.active():
            return actions
        robot = vec_env.unwrapped.scene["robot"]
        if self.joint_indices is None:
            names = list(robot.data.joint_names)
            self.joint_indices = {
                name: names.index(name)
                for name in self.RIGHT_ARM_JOINTS
                if name in names
            }
            print(f"[udp-policy] arm override joint map={self.joint_indices}")

        default_pos = robot.data.default_joint_pos[0]
        current_pos = robot.data.joint_pos[0]
        max_delta = max(0.0, float(args_cli.arm_max_delta_per_step))
        for name, target_pos in self.latest_positions.items():
            joint_index = self.joint_indices.get(name) if self.joint_indices else None
            if joint_index is None:
                continue
            if name not in self.applied_positions:
                self.applied_positions[name] = float(current_pos[joint_index])
            delta = float(target_pos) - self.applied_positions[name]
            if max_delta > 0.0:
                delta = max(-max_delta, min(max_delta, delta))
            self.applied_positions[name] += delta
            raw_action = (
                self.applied_positions[name] - float(default_pos[joint_index])
            ) / args_cli.arm_action_scale
            actions[0, joint_index] = raw_action
        return actions


class HandReachDebug:
    def __init__(self, scene_runtime: SceneRuntime | None):
        self.scene_runtime = scene_runtime
        self.body_indices: dict[str, int] | None = None
        self.last_printed_names = False
        self.output_path = pathlib.Path("logs/hand_reach_debug_latest.json")

    def _resolve_body_indices(self, robot) -> dict[str, int]:
        names = []
        if hasattr(robot.data, "body_names"):
            names = list(robot.data.body_names)
        elif hasattr(robot, "body_names"):
            names = list(robot.body_names)
        result = {
            name: index
            for index, name in enumerate(names)
            if any(token in name.lower() for token in ("right", "wrist", "hand"))
        }
        if not self.last_printed_names:
            print(f"[udp-policy][hand-debug] candidate bodies={result}")
            self.last_printed_names = True
        return result

    def update(self, vec_env, timestep: int) -> None:
        if args_cli.hand_debug_interval <= 0 or timestep % args_cli.hand_debug_interval != 0:
            return
        robot = vec_env.unwrapped.scene["robot"]
        if self.body_indices is None:
            self.body_indices = self._resolve_body_indices(robot)
        if not self.body_indices:
            return
        body_pos = robot.data.body_pos_w[0].detach().cpu()
        button = None
        if self.scene_runtime is not None:
            button = self.scene_runtime.centers_by_name.get("red_button_1")
        lines = []
        latest = {
            "timestep": timestep,
            "button": button,
            "bodies": {},
        }
        for name, index in self.body_indices.items():
            pos = body_pos[index].tolist()
            detail = f"{name}={[round(float(v), 3) for v in pos]}"
            body_entry = {"pos": [float(v) for v in pos]}
            if button is not None:
                dist = math.dist([float(v) for v in pos], [float(v) for v in button[:3]])
                detail += f" dist_to_red_button_1={dist:.3f}"
                body_entry["dist_to_red_button_1"] = float(dist)
            latest["bodies"][name] = body_entry
            lines.append(detail)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = self.output_path.with_suffix(".json.tmp")
        tmp_path.write_text(json.dumps(latest), encoding="utf-8")
        tmp_path.replace(self.output_path)
        print("[udp-policy][hand-debug] " + " | ".join(lines))


class ScriptedManipulationIO:
    """Small UDP endpoint for demo-time tabletop object animation.

    This is intentionally separate from the locomotion policy. It gives the
    state machine a reliable first demo path; later it can be replaced by arm
    IK or a learned manipulation policy without changing Nav2.
    """

    def __init__(self, scene_runtime: SceneRuntime | None):
        self.scene_runtime = scene_runtime
        self.enabled = scene_runtime is not None and not args_cli.disable_manipulation_udp
        self.socket: socket.socket | None = None
        self.reply_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.reply_target: tuple[str, int] | None = None
        self.request_id = ""
        self.keyframes: list[tuple[float, list[float]]] = []
        self.active = False
        self.start_wall_time = 0.0
        self.last_phase_index = -1

        if self.enabled:
            self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.socket.bind(("0.0.0.0", args_cli.manip_udp_port))
            self.socket.setblocking(False)

    def poll(self) -> None:
        if not self.enabled or self.socket is None:
            return
        while True:
            try:
                data, addr = self.socket.recvfrom(65535)
            except BlockingIOError:
                return
            try:
                payload = json.loads(data.decode("utf-8"))
            except json.JSONDecodeError as exc:
                print(f"[udp-policy][WARN] bad manipulation UDP JSON: {exc}")
                continue
            self._handle_payload(payload, addr)

    def update(self) -> None:
        if not self.active or not self.keyframes or self.scene_runtime is None:
            return
        elapsed = time.monotonic() - self.start_wall_time
        final_time, final_pos = self.keyframes[-1]
        pick_name = self.scene_runtime.manipulation.get("pick_object", {}).get("name", "pick_cube")
        prim_path = self.scene_runtime.prim_paths_by_name.get(pick_name)
        if not prim_path:
            self._send_status("error", f"missing pick object prim: {pick_name}")
            self.active = False
            return

        if elapsed >= final_time:
            set_box_center(self.scene_runtime.stage, prim_path, final_pos)
            self.active = False
            self._send_status("done", "pick_place complete")
            print(f"[udp-policy] scripted pick_place done request_id={self.request_id}")
            return

        previous = self.keyframes[0]
        phase_index = 0
        for index, keyframe in enumerate(self.keyframes[1:], start=1):
            if elapsed <= keyframe[0]:
                phase_index = index
                current = keyframe
                break
            previous = keyframe
        else:
            current = self.keyframes[-1]

        t0, p0 = previous
        t1, p1 = current
        alpha = 0.0 if t1 <= t0 else max(0.0, min(1.0, (elapsed - t0) / (t1 - t0)))
        alpha = alpha * alpha * (3.0 - 2.0 * alpha)
        pos = [p0[i] + alpha * (p1[i] - p0[i]) for i in range(3)]
        set_box_center(self.scene_runtime.stage, prim_path, pos)

        if phase_index != self.last_phase_index:
            self.last_phase_index = phase_index
            self._send_status("running", f"phase {phase_index}/{len(self.keyframes) - 1}")

    def _handle_payload(self, payload: dict, addr: tuple[str, int]) -> None:
        action = payload.get("action", "")
        self.request_id = str(payload.get("request_id", ""))
        reply_port = payload.get("reply_port")
        reply_host = payload.get("reply_host", addr[0])
        self.reply_target = (str(reply_host), int(reply_port)) if reply_port is not None else None

        if action == "status":
            self._send_status("running" if self.active else "idle", "status")
            return
        if action == "reset_cube":
            self._reset_cube()
            self._send_status("done", "cube reset")
            return
        if action == "press_button":
            self._press_button(str(payload.get("button", "")))
            return
        if action != "pick_place":
            self._send_status("error", f"unknown action: {action}")
            return

        if self.scene_runtime is None:
            self._send_status("error", "no obstacle scene loaded")
            return
        try:
            self.keyframes = self._build_pick_place_keyframes(float(payload.get("duration_scale", 1.0)))
        except (KeyError, TypeError, ValueError) as exc:
            self._send_status("error", f"cannot build pick_place sequence: {exc}")
            return

        self.active = True
        self.start_wall_time = time.monotonic()
        self.last_phase_index = -1
        self._send_status("accepted", "pick_place started")
        print(f"[udp-policy] scripted pick_place started request_id={self.request_id}")

    def _press_button(self, button_name: str) -> None:
        if self.scene_runtime is None:
            self._send_status("error", "no obstacle scene loaded")
            return
        prim_path = self.scene_runtime.prim_paths_by_name.get(button_name)
        if not prim_path:
            self._send_status("error", f"missing button prim: {button_name}")
            return
        set_box_color(self.scene_runtime.stage, prim_path, (0.25, 0.0, 0.0))
        self._send_status("done", f"button pressed: {button_name}")
        print(f"[udp-policy] button pressed: {button_name}")

    def _build_pick_place_keyframes(self, duration_scale: float) -> list[tuple[float, list[float]]]:
        if self.scene_runtime is None:
            raise ValueError("no scene runtime")
        duration_scale = max(0.25, min(4.0, duration_scale))
        pick = self.scene_runtime.manipulation["pick_object"]
        place = self.scene_runtime.manipulation["place_target"]
        pick_center = [float(v) for v in pick["center"]]
        pick_size = [float(v) for v in pick["size"]]
        place_center = [float(v) for v in place["center"]]
        place_size = [float(v) for v in place["size"]]
        final_center = [
            place_center[0],
            place_center[1],
            place_center[2] + 0.5 * place_size[2] + 0.5 * pick_size[2] + 0.015,
        ]
        lift_z = max(pick_center[2], final_center[2]) + 0.48
        waypoints = [
            pick_center,
            [pick_center[0], pick_center[1], lift_z],
            [pick_center[0], pick_center[1], lift_z],
            [place_center[0], place_center[1], lift_z],
            [final_center[0], final_center[1], final_center[2] + 0.16],
            final_center,
        ]
        times = [0.0, 0.8, 1.25, 2.8, 3.6, 4.4]
        return [(time_value * duration_scale, point) for time_value, point in zip(times, waypoints)]

    def _reset_cube(self) -> None:
        if self.scene_runtime is None:
            return
        pick = self.scene_runtime.manipulation.get("pick_object", {})
        prim_path = self.scene_runtime.prim_paths_by_name.get(pick.get("name", "pick_cube"))
        if prim_path and "center" in pick:
            set_box_center(self.scene_runtime.stage, prim_path, pick["center"])
        self.active = False

    def _send_status(self, status: str, message: str) -> None:
        if self.reply_target is None:
            return
        payload = {
            "request_id": self.request_id,
            "status": status,
            "message": message,
            "active": self.active,
        }
        self.reply_socket.sendto(json.dumps(payload).encode("utf-8"), self.reply_target)


def main():
    env_cfg = parse_env_cfg(
        args_cli.task,
        device=args_cli.device,
        num_envs=args_cli.num_envs,
        use_fabric=not args_cli.disable_fabric,
        entry_point_key="play_env_cfg_entry_point",
    )
    env_cfg.scene.num_envs = 1
    env_cfg.observations.policy.enable_corruption = False
    if hasattr(env_cfg.observations, "critic"):
        env_cfg.observations.critic.enable_corruption = False
    env_cfg.episode_length_s = args_cli.episode_length_s
    env_cfg.commands.base_velocity.resampling_time_range = (1.0e9, 1.0e9)
    env_cfg.commands.base_velocity.rel_standing_envs = 0.0
    env_cfg.commands.base_velocity.rel_heading_envs = 0.0
    env_cfg.commands.base_velocity.heading_command = False
    if hasattr(env_cfg, "events"):
        # Training-time perturbations make demos look like the robot is
        # randomly leaning or drifting. Disable them for Nav2 deployment.
        for event_name in ("push_robot", "base_external_force_torque", "add_base_mass"):
            if hasattr(env_cfg.events, event_name):
                setattr(env_cfg.events, event_name, None)

    agent_cfg: RslRlOnPolicyRunnerCfg = cli_args.parse_rsl_rl_cfg(args_cli.task, args_cli)
    checkpoint_path = resolve_checkpoint(agent_cfg)

    env = gym.make(args_cli.task, cfg=env_cfg)
    if isinstance(env.unwrapped, DirectMARLEnv):
        env = multi_agent_to_single_agent(env)
    vec_env = RslRlVecEnvWrapper(env, clip_actions=agent_cfg.clip_actions)
    scene_runtime = spawn_obstacle_scene(vec_env, args_cli.scene_json)

    runner = OnPolicyRunner(vec_env, agent_cfg.to_dict(), log_dir=None, device=agent_cfg.device)
    print(f"[udp-policy] loading checkpoint: {checkpoint_path}")
    load_runner_checkpoint_compat(runner, checkpoint_path)
    policy = runner.get_inference_policy(device=vec_env.unwrapped.device)

    obs = get_obs(vec_env)
    set_camera_to_robot(vec_env)
    udp_io = UdpPolicyIO()
    manip_io = ScriptedManipulationIO(scene_runtime)
    arm_io = ArmOverrideUdpIO()
    hand_debug = HandReachDebug(scene_runtime)
    dt = vec_env.unwrapped.step_dt
    timestep = 0

    print(f"[udp-policy] listening for command UDP on :{args_cli.cmd_udp_port}")
    if manip_io.enabled:
        print(f"[udp-policy] listening for scripted manipulation UDP on :{args_cli.manip_udp_port}")
    elif args_cli.disable_manipulation_udp:
        print("[udp-policy] scripted manipulation UDP disabled")
    else:
        print("[udp-policy] scripted manipulation UDP inactive because no scene_json was loaded")
    if arm_io.enabled:
        print(f"[udp-policy] listening for MoveIt Servo arm UDP on :{args_cli.arm_udp_port}")
    else:
        print("[udp-policy] MoveIt Servo arm UDP disabled")
    print(f"[udp-policy] publishing odom UDP to {udp_io.odom_target}")
    print(
        "[udp-policy] command clamps: "
        f"vx=[{args_cli.min_vx}, {args_cli.max_vx}], "
        f"|vy|<={args_cli.max_abs_vy}, |wz|<={args_cli.max_abs_wz}"
    )
    print(
        "[udp-policy] command timeout: "
        + ("disabled" if args_cli.disable_command_timeout else f"{args_cli.command_timeout}s")
    )
    print(f"[udp-policy] continuous navigation episode_length_s={args_cli.episode_length_s}")

    try:
        while simulation_app.is_running():
            start_time = time.time()
            manip_io.poll()
            arm_io.poll()
            command = udp_io.poll_command(vec_env.unwrapped.device, env_cfg)
            if arm_io.active():
                command.zero_()
            live_command = enforce_command(vec_env, command)
            with torch.inference_mode():
                actions = policy(obs)
                actions = arm_io.apply(vec_env, actions)
                obs, _, _, _ = vec_env.step(actions)
            manip_io.update()

            sim_time = float(vec_env.unwrapped.common_step_counter * vec_env.unwrapped.step_dt)
            udp_io.publish_odom(vec_env, sim_time)
            hand_debug.update(vec_env, timestep)

            if args_cli.command_print_interval > 0 and timestep % args_cli.command_print_interval == 0:
                root = vec_env.unwrapped.scene["robot"]
                root_lin_vel_b = root.data.root_lin_vel_b[0].tolist()
                root_ang_vel_b = root.data.root_ang_vel_b[0].tolist()
                age = udp_io.command_age()
                age_text = "inf" if age == float("inf") else f"{age:.3f}s"
                print(
                    f"[udp-policy] step={timestep} cmd={live_command[0].tolist()} "
                    f"raw_cmd={udp_io.latest_cmd.tolist()} cmd_age={age_text} "
                    f"timed_out={udp_io.is_timed_out()} received={udp_io.received_cmd_count} "
                    f"root_lin_vel_b={root_lin_vel_b} root_ang_vel_b={root_ang_vel_b}"
                )
            timestep += 1

            sleep_time = dt - (time.time() - start_time)
            if args_cli.real_time and sleep_time > 0:
                time.sleep(sleep_time)
    finally:
        vec_env.close()


if __name__ == "__main__":
    try:
        main()
    finally:
        simulation_app.close()
